// <auto-generated />
using System;
using Imposter.Infrastructure.Dbcontext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Imposter.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251121204259_setnull")]
    partial class setnull
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Imposter.Core.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("Connections")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.HasKey("PlayerId");

                    b.HasIndex("RoomId");

                    b.ToTable("players");
                });

            modelBuilder.Entity("Imposter.Core.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<Guid?>("HostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("InGame")
                        .HasColumnType("bit");

                    b.Property<string>("SecretWordText")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.HasKey("RoomId");

                    b.HasIndex("HostId");

                    b.HasIndex("SecretWordText");

                    b.ToTable("rooms");
                });

            modelBuilder.Entity("Imposter.Core.Domain.Entities.SecretWord", b =>
                {
                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.HasKey("Text");

                    b.ToTable("secretWords");
                });

            modelBuilder.Entity("Imposter.Core.Domain.Entities.Player", b =>
                {
                    b.HasOne("Imposter.Core.Domain.Entities.Room", "Room")
                        .WithMany("Players")
                        .HasForeignKey("RoomId");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Imposter.Core.Domain.Entities.Room", b =>
                {
                    b.HasOne("Imposter.Core.Domain.Entities.Player", "Host")
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Imposter.Core.Domain.Entities.SecretWord", "SecretWord")
                        .WithMany()
                        .HasForeignKey("SecretWordText");

                    b.Navigation("Host");

                    b.Navigation("SecretWord");
                });

            modelBuilder.Entity("Imposter.Core.Domain.Entities.Room", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
