// <auto-generated />
using System;
using Imposter.Infrastructure.Dbcontext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Imposter.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251127002006_addlistofchoices")]
    partial class addlistofchoices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Imposter.Core.Domain.Entities.Connection", b =>
                {
                    b.Property<string>("ConnectionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("playerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("roomId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ConnectionId");

                    b.HasIndex("playerId");

                    b.HasIndex("roomId");

                    b.ToTable("connections");
                });

            modelBuilder.Entity("Imposter.Core.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.HasKey("PlayerId");

                    b.HasIndex("RoomId");

                    b.ToTable("players");
                });

            modelBuilder.Entity("Imposter.Core.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Category")
                        .HasColumnType("int");

                    b.Property<Guid?>("HostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ImposterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("InGame")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SecretWordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.HasKey("RoomId");

                    b.HasIndex("HostId");

                    b.HasIndex("ImposterId");

                    b.HasIndex("SecretWordId");

                    b.ToTable("rooms");
                });

            modelBuilder.Entity("Imposter.Core.Domain.Entities.SecretWord", b =>
                {
                    b.Property<Guid>("SecretWordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("Choices")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SecretWordId");

                    b.ToTable("secretWords");
                });

            modelBuilder.Entity("Imposter.Core.Domain.Entities.Connection", b =>
                {
                    b.HasOne("Imposter.Core.Domain.Entities.Player", "Player")
                        .WithMany("Connections")
                        .HasForeignKey("playerId");

                    b.HasOne("Imposter.Core.Domain.Entities.Room", "Room")
                        .WithMany("connections")
                        .HasForeignKey("roomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Player");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Imposter.Core.Domain.Entities.Player", b =>
                {
                    b.HasOne("Imposter.Core.Domain.Entities.Room", "Room")
                        .WithMany("Players")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Imposter.Core.Domain.Entities.Room", b =>
                {
                    b.HasOne("Imposter.Core.Domain.Entities.Player", "Host")
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Imposter.Core.Domain.Entities.Player", "Imposter")
                        .WithMany()
                        .HasForeignKey("ImposterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Imposter.Core.Domain.Entities.SecretWord", "SecretWord")
                        .WithMany()
                        .HasForeignKey("SecretWordId");

                    b.Navigation("Host");

                    b.Navigation("Imposter");

                    b.Navigation("SecretWord");
                });

            modelBuilder.Entity("Imposter.Core.Domain.Entities.Player", b =>
                {
                    b.Navigation("Connections");
                });

            modelBuilder.Entity("Imposter.Core.Domain.Entities.Room", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("connections");
                });
#pragma warning restore 612, 618
        }
    }
}
